name: Cars.APP
version: 0.1.10
description: Car selling application for mango services.
author: Louise van der Lith
repository: https://github.com/louisevanderlith/cars
environment:
  sdk: '>=2.0.0 < 3.0.0'
dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers:  '>=2.6.1 <3.0.0'
dependencies:
  mango_ui: '^1.0.3'
  mango_vin: '^1.0.0'
  mango_vehicle: '^1.0.7'
  mango_artifact: '^1.0.0'
  modern_charts: '^0.1.19'